server:
  port: 38082

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: 'etl-data'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kafka
    username: root
    password: password
  jpa:
    database: mysql
    hibernate.ddl-auto: 'create-drop'
    generate-ddl: true
    show-sql: true